title: "Abe Porschet"
description: "Statistics, books, art"
url: "https://yourusername.github.io"

author:
  name: "Abe Porschet"
  email: "abe.porschet@icloud.com"

# Social links (optional)
social:
  github: "aporsch1"
  email: "abe.porschet@icloud.com"
